// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  req

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CatReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CatReq ) UnmarshalJSON([]byte) error { return nil }
func ( CatReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CatReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CatReq *CatReq
