// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package req

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB1a2c735DecodeAwesomeProjectInternalPkgHandlerDtoReq(in *jlexer.Lexer, out *SignIn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1a2c735EncodeAwesomeProjectInternalPkgHandlerDtoReq(out *jwriter.Writer, in SignIn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignIn) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1a2c735EncodeAwesomeProjectInternalPkgHandlerDtoReq(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignIn) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1a2c735EncodeAwesomeProjectInternalPkgHandlerDtoReq(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignIn) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1a2c735DecodeAwesomeProjectInternalPkgHandlerDtoReq(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignIn) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1a2c735DecodeAwesomeProjectInternalPkgHandlerDtoReq(l, v)
}
